Updates docs to adoc, and licenses around
d4l-data4life/d4l-fhir-ios pull request #19
Opened 2021-09-14 15:38 UTC by alessioborraccino

## Description

## Motivation and Context

## How is it being implemented?

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the changelog accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-15 17:33 UTC, bitPogo requested changes
Please see below.

2021-09-15 17:33 UTC, bitPogo commented on CHANGELOG.adoc
> +See link:{link-repository}/compare/v1.16.0...main[changeset]
Is the version correct? - the lastest release states 0.22.1

2021-09-15 17:33 UTC, bitPogo commented on CHANGELOG.adoc
> +== link:{link-repository}/releases/tag/v0.23.0[0.23.0]
Is the version correct? - the lastest release states 0.22.1

2021-09-15 17:33 UTC, bitPogo commented on DEVELOPING.adoc
> +STU3 models/tests and r4 protocol conformations/tests are autogenerated via the parser and sourcery.
Nitpick: R4, I suppose

2021-09-15 17:33 UTC, bitPogo commented on DEVELOPING.adoc
> +NOTE: Prepare release script will fail if there is no new version defined in the changelog
Nitpick: `The Prepare release script [...]`

2021-09-15 17:33 UTC, bitPogo commented on DEVELOPING.adoc
> +=== Prepare release script steps
Maybe put this before `Steps` it is a bit confusing to read it in this order in my opinion.

2021-09-15 17:33 UTC, bitPogo commented on DEVELOPING.adoc
> +* Create GitHub release draft with all of the information from link:CHANGELOG.adoc[CHANGELOG]
`Create a GitHub release draft with all of the information from the CHANGELOG`

2021-09-15 17:33 UTC, bitPogo commented on DEVELOPING.adoc
> +Documentation is generated using Asciidoctor, all of the resoures can be found in link:asciidoc/[asciidoc], and generated HTML documentation can be found in link:docs/(docs).
Maybe call it just `docs` or something simply because ASCIIDoc is a format and not a common term.

2021-09-15 17:33 UTC, bitPogo commented on DEVELOPING.adoc
> +Documentation is generated using Asciidoctor, all of the resoures can be found in link:asciidoc/[asciidoc], and generated HTML documentation can be found in link:docs/(docs).
Also `link:docs/(docs)` is not displayed correctly.

2021-09-15 17:33 UTC, bitPogo commented on README.adoc
> +:link-repository: https://github.com/d4l-data4life/d4l-fhir-ios
This should be now on line 2.

2021-09-15 17:33 UTC, bitPogo commented on README.adoc
> +[Apple-FHIR](https://github.com/apple/FHIRModels) R4 models were (tepmorarily) ported over.
Both are not display correctly I suppose.

2021-09-15 17:33 UTC, bitPogo commented on README.adoc
> +    </p>
Please take a look into the latest iteration of the Header in the README. An example can be found [here](https://github.com/d4l-data4life/hc-data-donation-sdk-kmp/pull/31).

2021-09-28 07:58 UTC, jose-cuadros-data4life approved these changes
Please consider @bitPogo comments, but apart of his comments I couldn't find any other issue

2021-11-18 09:11 UTC, alessioborraccino commented on CHANGELOG.adoc
> +== link:{link-repository}/releases/tag/v0.23.0[0.23.0]
yes its coming

2021-11-18 09:11 UTC, alessioborraccino commented on CHANGELOG.adoc
> +See link:{link-repository}/compare/v1.16.0...main[changeset]
done

2021-11-18 09:12 UTC, alessioborraccino commented on DEVELOPING.adoc
> +STU3 models/tests and r4 protocol conformations/tests are autogenerated via the parser and sourcery.
👍

2021-11-18 09:12 UTC, alessioborraccino commented on DEVELOPING.adoc
> +NOTE: Prepare release script will fail if there is no new version defined in the changelog
👍

2021-11-18 09:14 UTC, alessioborraccino commented on DEVELOPING.adoc
> +=== Prepare release script steps
Its more relevant to the manual steps just described, the script steps are more if you want to go in detail on it

2021-11-18 09:16 UTC, alessioborraccino commented on DEVELOPING.adoc
> +Documentation is generated using Asciidoctor, all of the resoures can be found in link:asciidoc/[asciidoc], and generated HTML documentation can be found in link:docs/(docs).
👍

2021-11-18 09:18 UTC, alessioborraccino commented on DEVELOPING.adoc
> +* Create GitHub release draft with all of the information from link:CHANGELOG.adoc[CHANGELOG]
👍

2021-11-18 09:18 UTC, alessioborraccino commented on README.adoc
> +:link-repository: https://github.com/d4l-data4life/d4l-fhir-ios
👍

2021-11-18 09:23 UTC, alessioborraccino commented on README.adoc
> +    </p>
👍

2021-11-18 10:24 UTC, bitPogo requested changes
Still nitpicks left

2021-11-18 10:24 UTC, bitPogo commented on CODE-OF-CONDUCT.adoc
> +:link-repository: https://github.com/d4l-data4life/d4l-sdk-ios
d4l-fhir-ios

2021-11-18 10:24 UTC, bitPogo commented on CONTRIBUTING.adoc
> +:link-repository: https://github.com/d4l-data4life/d4l-sdk-ios
d4l-fhir-ios

2021-11-18 10:24 UTC, bitPogo commented on CONTRIBUTING.adoc
> +- *Remove* | for removed features or functionality
- `|`

2021-11-18 10:24 UTC, bitPogo commented on CONTRIBUTING.adoc
> +Contributor License Agreement. Please get in contact with mailto:&#109;o&#98;&#x69;&#x6c;&#x65;&#x40;&#100;&#x61;&#x74;a&#52;&#x6c;&#105;f&#101;&#46;&#99;a&#114;e[&#109;o&#98;&#x69;&#x6c;&#x65;&#x40;
Is the mail to still valid?

2021-11-18 16:57 UTC, bitPogo approved these changes
LGTM

2021-11-18 17:08 UTC, merged